### ISSUE TITLE
Bug:  Lever does not operate in 0.91 Example scene

### ISSUE THREAD

**Issue by pkarjala** [TomorrowTodayLabs/NewtonVR#81] opened 2016-11-10 02:24 UTC
In the latest sample scene available for the Vive, the Lever that can be used to launch the rocket can no longer be interacted with by the user.  It appears that the grabber interaction does not want to correctly grasp the handle; instead, when using the grip buttons and pressing them while having the controller hovering over the lever, it instead turns dark and collides with it like a normal physics interaction.

The intended functionality is that the controller allows the user to pull the lever when the grip buttons are pressed.

**Comment by IntegersOfK** [comment] 2016-11-10 16:44
I also have the problem you've described, I created a thread in the support system:
https://newtonvr.readme.io/discuss/5823df6e7d55d4230031e195

Also the spinner isn't working as intended, see my video:
https://www.youtube.com/watch?v=TzaU3W-mjBY

**Comment by SmartCarrion** [comment] 2016-11-10 17:47
I can't quite tell from the video because you are moving so fast and there
is no indication of when you push the button...but are you actually
sticking the controller into the wheel before you hit the grab button? It
kind of looks like you hit the grab button and then reach out for it.

**Comment by IntegersOfK** [comment] 2016-11-10 18:28
That's a fair criticism of my video, it doesn't seem like I'm ever squeezing 'inside' the wheel but that's just because the model does not change to the solid colour when the controller is colliding with it/inside the wheel during a squeeze. I have tried the example scene from before this latest update and because of this I am aware of how it's supposed to work (one puts the whole controller into the wheel, squeezes, and then it'll turn).

I can confirm for you that I have tried starting the squeeze inside, outside, both controllers, using another rigid-bodied item instead of controller, etc.

Similarly, the lever doesn't let me put the controller 'inside' of it and squeeze to grab it, which is why I feel these issues are related enough to hop into @pkarjala's issue thread here.

**Comment by pkarjala** [comment] 2016-11-10 23:41
I can confirm that the letter wheel also does not function as intended, as described by @IntegersOfK .

**Comment by keithbradner** [comment] 2016-11-10 23:49
Thanks guys, we'll take a look at it as soon as possible.

**Comment by pkarjala** [comment] 2016-11-10 23:53
I will not have access to a Vive system until next week, but I can state that the test was performed with the latest update of the Vive libraries downloaded through Unity 3d as of Monday, Nov 7th; perhaps there is a breaking change there.

Thanks for your work on this library!

**Comment by AdamBaileyAIE** [comment] 2016-11-13 05:52
I can confirm this issue as well.  Using Touch controllers I cannot spin the wheel or move the lever using either the Oculus or SteamVR sdks.  In addition picking up objects seems broken using Oculus SDK.  I am able to pick objects up, but they shake around violently (like they are colliding with the hands or something) and when you let go they go flying off.  That functionality works as expected using SteamVR.

**Comment by keithbradner** [comment] 2016-11-15 01:55
Sorry about that, was an error when I moved back to doing the velocity changes inside fixed update. Should be fixed in 0.94. (released just now).

**Closed as completed by keithbradner** 2016-11-15 01:55 UTC

**Comment by AdamBaileyAIE** [comment] 2016-11-15 02:16
All working perfectly using Touch and Oculus SDK. :D

edit: and of course thanks for the quick resolve!

**Comment by pkarjala** [comment] 2016-11-15 06:01
Verified working on Vive, thank you for the fix!
