### ISSUE TITLE
Attached Objects Jitter

### ISSUE THREAD

**Issue by smackroot** [TomorrowTodayLabs/NewtonVR#52] opened 2016-08-15 15:49 UTC
Hello there,

at first I would really like to thank you for your amazing work on NewtonVR. It really helped me a lot, and I had a blast with the Physics applied on my Objects in VR.

However, I am having a problem with serious Jitter when i attach an object to the controller via the grip button. Slight movements with the controller will translate to massive jumpy movements of the objects and eventually will break the attachment and the object will be launched into the open. Using the controller as an rigidbody or other physical interactions with other objects are just working as intended. Only the controller attachment is wonky.

I only have this problem with some models from me and also only with specific meshes. For Example: I have a fridge-like Object and some tubes i made myself. When i attach to the tubes I dont experience the jitter, the fridge itself however will go mad when i attach it.

I thought it would be linked to amounts of vertices or different materials on an object, but the tubes with a lot more vertices are not causing issues. Also removing the  ~8 materials from the fridge did not resolve the issue.
Changing the physical values of the rigidbodies also did not help, it even seems that they do not have any effect when attached to the controller (probably intended). The object just jitters massively.

Am I overlooking something? I just have the feeling that there is something wrong with my polygons, but I simply can not imagine what it is.

Many thanks , Best Regards and I hope I got my point across!
Smack

**Comment by flarb** [comment] 2016-08-17 01:43
I see this as well. I thought maybe it's an artifact of the way Netwon makes held objects follow the hand?

**Comment by SmartCarrion** [comment] 2016-08-17 01:48
I get it too, but only when performance drops below 90fps. It gets really bad around 45 fps, and becomes unplayable.

**Comment by flarb** [comment] 2016-08-17 02:23
I see it in the demo scene. Especially on the guns.

**Comment by Cratesmith** [comment] 2016-08-17 02:58
There's a few errors in how newtonVR makes non-kinematic objects follow the
controller. These are mostly only noticable for objects with interaction
points but happens on everything. The angular/linear velocituies are being
updated an inconsistent number of times per physics frame which is why it
jitters more at lower frame rates.

I have a fixed version in my branch but it behaves slightly differently, a
little more "lateral sway" but less jittering when colliding with objects. I
can submit a pull request from my branch with the fix later if it helps.

**Comment by keithbradner** [comment] 2016-08-17 03:11
Hm, this should be fixed with the change from FixedUpdate to OnNewPoses. The velocity algorithm is no longer dependent on the physics steps, but on the OnNewPoses steps. Doing it via FixedUpdate was causing us issues at low framerates so we switched it. I'll try and artificially induce low framerate and see how it goes. However, other things are going to break if your framerate is dropping below 90.

**Comment by flarb** [comment] 2016-08-17 03:54
I'm seeing this at 90fps on the test scene, though. I'm using an AMD Fury X if that's an issue.

**Comment by keithbradner** [comment] 2016-08-17 04:23
Oh crap, yeah. I have been testing at lower framerates recently :P We'll take a look at this first thing in the morning.

**Comment by Cratesmith** [comment] 2016-08-17 05:34
I've attached our version NVInteractableItem for you to check out.

We went back to applying changes in fixed update with a few other changes
- Rotation may be frozen while held
- Fixed a bug where angle in degrees was being applied to
  Rigidbody.angularVelocity instead of radians
- We sweep test the object's motion. If it didn't collide it's moved
  kinematically. (worse performance, but gives very smooth movement)
- Interaction point can be applied in different reference spaces (eg, guns
  feel strange if they match the rotation of the grip of the controller
  rather than the "pointing direction")

Edit: sorry that didn't attach as intended. See here:
http://pastebin.com/EyMrRhpe

**Comment by smackroot** [comment] 2016-08-17 16:55
Thanks for the Feedback. I tried your script but to no avail (at least I can grab the object and hold it with a very steady hand).
Additionally I am definitely above 90 fps (96 in Unity), and do not notice any overall lag or reprojection (I am running on a GTX 980TI and an 6600K).

I will attach a GIF showing one of the objects thats causes problems [GIF](https://imgur.com/a/Ix6Mz) As not every object suffers from this issue I am afraid something is wrong with my 3D-Models. But I can´t tell what it could be.

**Comment by keithbradner** [comment] 2016-08-17 17:40
This looks like a problem with all objects. We're working on a fix now

**Comment by naabel** [comment] 2016-08-17 19:43
We've pushed an additional change to the Velocity and AngularVelocity
update sequence to correct the high frame rate jitter issue. They're back
to running in FixedUpdate(), instead of in OnNewPoseApplied(). It fixes
things on our end, but please test and let us know if it fixes thing for
you.

**Comment by smackroot** [comment] 2016-08-17 20:26
Many thanks for the Update, I really appreciate your efforts, but sadly this does not work either for my problem. At this point I feel like I am doing some super basic stuff terribly wrong :D

Did you experience the same heavy judder as me?  GIF : ([https://imgur.com/a/Ix6Mz](https://imgur.com/a/Ix6Mz))

**Comment by naabel** [comment] 2016-08-17 20:53
It's the weirdest thing. Keith saw it, but I haven't so far. I'm writing new code to take only the last pose update, but still apply it in FixedUpdate, but I'm wondering if I'm going the wrong direction. Thanks for the help though, sorry the fix didn't work :(

**Comment by Cratesmith** [comment] 2016-08-17 21:46
Just a thought... if you're getting this at high frame rate check that
interpolation is off for your rigidbody. Because of the way velocity is
applied interpolation will be quite wrong (especially if gravity is enabled
while the object is held).
Also I'm quite curious if the sweeptest version I made wasn't stable as it
uses rigidbody.setpos/setrot when there's no likely collision in the next
frame, which should be jitter free.

**Comment by keithbradner** [comment] 2016-08-18 00:39
I submitted another possible fix so item velocity only gets updated once per rendered frame (still in fixedupdate though). We're trying to find a computer we can get a solid repo on. Let me know if this fixes the problem for you guys.

**Comment by smackroot** [comment] 2016-08-18 17:38
Thank you so much for all your efforts, but I found the solution for me. For most of you, this might be absolute common knowledge, but my objects had the pivot point being way off center. So they have been far away from the object. Putting the pivot point in 3DS max now directly into the object, solved all my issues!

Now I continue working with the fabulous NewtonVR!

**Comment by flarb** [comment] 2016-08-18 19:48
Yep, it works fine for me now!

**Comment by SmartCarrion** [comment] 2016-08-31 05:59
Man, this sounded like a great fix but it didn't work for me at all!  maybe made it worse even! I made a video to show the issue: https://youtu.be/F5OISF9Xtt0

I just tried it in the test scene with your debug code and it happens there too, so i'm doubting it is just some setting in my scene.  The more you turn up the 'debug sleep per frame' the worse it gets.  I'm on a geforce 970 and i7 6700k

**Comment by SmartCarrion** [comment] 2016-08-31 06:24
Is there someplace we need to divide the velocity by time.deltatime or something?

**Comment by bgr** [comment] 2016-09-27 23:27
I'm seeing this as well, heavy sideways jitter when picking up a gun in the example scene.

**Comment by SmartCarrion** [comment] 2016-09-27 23:35
Thank you for confirming the issue!  My game is at 90fps most of the time and this issue doesn't ruin it most of the time, but I just don't see a reason why this bug needs to exist. For the times when there is a frame rate dip, or some background process causes an issue, or any other issue comes up...picking up Newton objects becomes a game breaking experience where the objects wildly fly back and forth from your hand.

I'd really don't want to ship my game with this kind of bug!

**Comment by SmartCarrion** [comment] 2016-09-27 23:39
By the way, if you are experiencing this in the editor, make sure you have 'Scene' view closed or covered by another window, or use 'Maximize on Play'.  Rendering scene view can have a huge performance hit.

**Comment by justonia** [comment] 2016-09-29 00:29
I was having a similar problem when messing around with a plank like object. The pivot point for the object was at the base of the mesh and as soon as I moved it to be exactly in the rigidbody center of mass I lost _alot_ of jitter. It makes sense when you look at the code and see how the rigidbody is being tracked to the hand. I suggest moving your pivots and see what happens.

**Comment by keithbradner** [comment] 2016-11-23 06:21
We've reverted to the old magic number method of fixing this. Will continue to look for better methods though!

**Closed as completed by keithbradner** 2016-11-23 06:21 UTC

**Comment by SmartCarrion** [comment] 2016-11-23 06:58
yup it is a lot more stable now.  I suppose an alternative would be to
switch methods on the fly if frames are taking too long.  I still think the
last method must have been missing a time.deltatime division somewhere, but
I haven't looked into that part of the code.  thanks for your work on the
big update, i'm excited to have one less system i have to rip out when
porting to other platforms!
